# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import os
import sys
import re
sys.path.insert(0, os.path.abspath('..'))

project = 'SynIM'
copyright = '2025, Guido Agapito'
author = 'Guido Agapito'

# Read version from _version.py (generated by setuptools_scm)
try:
    from synim._version import version as __version__
except ImportError:
    # fallback: read from pyproject.toml if _version.py is missing (e.g. on RTD)
    try:
        import tomllib
    except ImportError:
        import tomli as tomllib
    with open(os.path.join(os.path.dirname(__file__), '..', 'pyproject.toml'), 'rb') as f:
        pyproject = tomllib.load(f)
    __version__ = pyproject.get('project', {}).get('version', '0.1.0')

# Mock imports for ReadTheDocs (SPECULA might not be available)
autodoc_mock_imports = ['specula']

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.autosummary',
              'sphinx.ext.coverage',
              'sphinx.ext.napoleon',
              'sphinx.ext.intersphinx',
              'sphinx_rtd_theme',
              'myst_parser',
              'nbsphinx',
              'numpydoc',
              ]

source_suffix = {
    '.rst': None,
    '.md': None,
}

intersphinx_mapping = {
    'numpy': ('https://docs.scipy.org/doc/numpy/', None),
    'scipy': ('https://docs.scipy.org/doc/scipy/reference/', None),
    'astropy': ('https://docs.astropy.org/en/stable/', None),
    }


templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

master_doc = 'index'

# General substitutions.

# The default replacements for |version| and |release|, also used in various
# other places throughout the built documents.
version = re.sub(r'\.dev-.*$', r'.dev', __version__)
release = __version__

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%B %d, %Y'


# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']


print("%s (VERSION %s)" % (project, version))

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = 'py:obj'